FROM redis/redis-stack-server:latest

COPY target/x86_64-unknown-linux-gnu/release/api-server /root/

COPY .env /root/
COPY api-token.json /root/
COPY start.sh /root/

RUN chmod a+x /root/start.sh
RUN chmod a+x /root/api-server

WORKDIR /root/

CMD  ./start.sh