@token=xZ5yXTRsRVTFXZXPrmbHd0aW9uIHR
@project=project1
@queue=q0
@delay=0
@ttl=36000
@tries=3
@ttr=60
@url=http://127.0.0.1:7766

# Change this to the real task id returned by push/get request.
@task_id=8a61754d-8fb3-414a-b976-e028f57e6371

# @name push a new task into the queue
# @param project
# @param queue
put {{url}}/queue-api/{{project}}/{{queue}}?delay={{delay}}&ttl={{ttl}}&tries={{tries}}
X-token: {{token}}

{
    "text": "text",
}

###

# @name get a task from the task queue
get {{url}}/queue-api/{{project}}/{{queue}}?ttr={{ttr}}
X-token: {{token}}

###

# @name Queue size
get {{url}}/queue-api/{{project}}/{{queue}}/size
X-token: {{token}}

###

# @name Delete Task
delete {{url}}/queue-api/{{project}}/{{queue}}/delete/{{task_id}}
X-token: {{token}}